Lmod has detected the following error: Cannot load module "cudnn/8.0.5.39"
without these module(s) loaded:
   cuda/11.0.2-4szlv2t

While processing the following module(s):
    Module fullname  Module Filename
    ---------------  ---------------
    cudnn/8.0.5.39   /gpfs/fs1/soft/swing/manual/modulefiles/cudnn/8.0.5.39.lua

environment: line 5: __conda_exe: command not found
STARTING HEAD at gpu1
Head node IP: 10.70.150.11
slurmstepd: error: execve(): start-head.sh: Permission denied
srun: error: gpu1: task 0: Exited with exit code 13
slurmstepd: error: execve(): start-worker.sh: Permission denied
srun: error: gpu2: task 0: Exited with exit code 13
Traceback (most recent call last):
  File "/gpfs/fs1/home/ac.gwilkins/energy-inference/job-scripts/argonne-swing/../../cuda/open-source-cuda-ray.py", line 1, in <module>
    from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline
  File "/home/ac.gwilkins/.conda/envs/fedsz2/lib/python3.11/site-packages/transformers/__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "/home/ac.gwilkins/.conda/envs/fedsz2/lib/python3.11/site-packages/transformers/dependency_versions_check.py", line 16, in <module>
    from .utils.versions import require_version, require_version_core
  File "/home/ac.gwilkins/.conda/envs/fedsz2/lib/python3.11/site-packages/transformers/utils/__init__.py", line 32, in <module>
    from .generic import (
  File "/home/ac.gwilkins/.conda/envs/fedsz2/lib/python3.11/site-packages/transformers/utils/generic.py", line 33, in <module>
    import jax.numpy as jnp
  File "/home/ac.gwilkins/.conda/envs/fedsz2/lib/python3.11/site-packages/jax/__init__.py", line 35, in <module>
    from jax import config as _config_module
  File "/home/ac.gwilkins/.conda/envs/fedsz2/lib/python3.11/site-packages/jax/config.py", line 17, in <module>
    from jax._src.config import config
  File "/home/ac.gwilkins/.conda/envs/fedsz2/lib/python3.11/site-packages/jax/_src/config.py", line 29, in <module>
    from jax._src import lib
  File "/home/ac.gwilkins/.conda/envs/fedsz2/lib/python3.11/site-packages/jax/_src/lib/__init__.py", line 87, in <module>
    version = check_jaxlib_version(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ac.gwilkins/.conda/envs/fedsz2/lib/python3.11/site-packages/jax/_src/lib/__init__.py", line 82, in check_jaxlib_version
    raise RuntimeError(msg)
RuntimeError: jaxlib version 0.4.24 is newer than and incompatible with jax version 0.3.22. Please update your jax and/or jaxlib packages.
